export type IconType = 'Ionicons' | 'Fontisto';

export interface IIcon {
  type: IconType;
  name: string;
}

export const IconBackgroundColors = [
  '#e32b2b',
  '#c27a7a',
  '#991414',
  '#520e0e',
  '#ffa412',
  '#c77b00',
  '#ff9e00',
  '#a38555',
  '#ffe72e',
  '#deb500',
  '#b09e10',
  '#82792e',
  '#96b038',
  '#acd615',
  '#9ec900',
  '#7b9c02',
  '#3ca616',
  '#299403',
  '#286313',
  '#19400b',
  '#54e3d5',
  '#259c90',
  '#00ad9c',
  '#0a5c54',
  '#4996bf',
  '#426e85',
  '#164963',
  '#07344a',
  '#4287f5',
  '#29569e',
  '#3d4654',
  '#2b41e3',
  '#7b29ab',
  '#a52bed',
  '#bf64f5',
  '#6a5378',
];

export const Icons: IIcon[] = [
  { type: 'Ionicons', name: 'ios-wallet' },
  { type: 'Ionicons', name: 'ios-airplane' },
  { type: 'Ionicons', name: 'ios-alarm' },
  { type: 'Ionicons', name: 'ios-at' },
  { type: 'Ionicons', name: 'ios-body' },
  { type: 'Ionicons', name: 'ios-book' },
  { type: 'Ionicons', name: 'ios-bed' },
  { type: 'Ionicons', name: 'ios-beer' },
  { type: 'Ionicons', name: 'ios-basketball' },
  { type: 'Ionicons', name: 'ios-checkmark' },
  { type: 'Ionicons', name: 'ios-trash' },
  { type: 'Ionicons', name: 'ios-basket' },
  { type: 'Ionicons', name: 'ios-bicycle' },
  { type: 'Ionicons', name: 'ios-briefcase' },
  { type: 'Ionicons', name: 'ios-cafe' },
  { type: 'Ionicons', name: 'ios-call' },
  { type: 'Ionicons', name: 'ios-car' },
  { type: 'Ionicons', name: 'ios-card' },
  { type: 'Ionicons', name: 'ios-cart' },
  { type: 'Ionicons', name: 'ios-cash' },
  { type: 'Ionicons', name: 'ios-cloud-circle' },
  { type: 'Ionicons', name: 'ios-color-palette' },
  { type: 'Ionicons', name: 'ios-fitness' },
  { type: 'Ionicons', name: 'ios-flame' },
  { type: 'Ionicons', name: 'ios-flash' },
  { type: 'Ionicons', name: 'ios-flask' },
  { type: 'Ionicons', name: 'ios-football' },
  { type: 'Ionicons', name: 'ios-globe' },
  { type: 'Ionicons', name: 'ios-laptop' },
  { type: 'Ionicons', name: 'ios-mail' },
  { type: 'Ionicons', name: 'ios-musical-notes' },
  { type: 'Ionicons', name: 'ios-phone-portrait' },
  { type: 'Ionicons', name: 'ios-pizza' },
  { type: 'Ionicons', name: 'ios-rocket' },
  { type: 'Ionicons', name: 'ios-shirt' },
  { type: 'Ionicons', name: 'ios-subway' },
  { type: 'Ionicons', name: 'ios-trophy' },
  { type: 'Ionicons', name: 'ios-water' },
  { type: 'Ionicons', name: 'ios-wine' },
];
